### PR TITLE
Enables course start and end dates

### PR DESCRIPTION
**Pull request by Genyus**
Courses can now have start and end dates defined and displayed

Screenshot 2023-06-28 at 05 37 05

### CODE REVIEW

**Comment by tanyapowell** [comment]
Err...which of the 522 files should I be looking at?

**Comment by Genyus** [comment]
Sorry, I shouldn't've asked for your review yet as I was only merging to develop (it was late, brain tired), but you can look at the [feature commit](https://github.com/CodingBlackFemales/wordpress/commit/434c41d7407bceacfcc7ff563713b3edb937dfe5)

**Comment by tanyapowell** [comment]
Gracias senor! Should this be on the group level (buddy boss) instead of the course level (learn dash)?

**Comment by Genyus** [comment]
Ah, I see what you mean. Hmm. Groups don't support similar properties, but I dug around a little and found the "Access expiration" course setting that controls how long a user retains access to a given course. When users are enrolled via groups, their access starts from when the course was enrolled into a group, or if the user registered after that happened, it starts from their registration date.

As such, the new start and end date fields might be redundant for our current use cases, but we could still retain this modification as the current behaviour will remain unchanged unless there's a future scenario where we decide to utilise them?

**Comment by tanyapowell** [comment]
Think I get what you mean. 

For the "Access expiration" course setting does this have to be applied on a per user basis, or can it be set for a whole group?

**Comment by tanyapowell** [comment]
Ok, I get what you mean. If we leave the functionality can displaying these dates be enabled/disabled by an end user?

**Comment by Genyus** [comment]
So these values will only be displayed if the new properties are set on a course, which won't apply to any in our current configuration. But the option will be there for future use should we ever need it

**Pull request merged**
