### PR TITLE
Fixes displayed number of inserted records

### PR DESCRIPTION
**Pull request by Genyus**
Previously showed number of batch requests issued instead of actual record count

### CODE REVIEW

**Comment by tanyapowell** [comment]
Is this pull request related to this [issue?](https://codingblackfemales.atlassian.net/browse/TECH-391?atlOrigin=eyJpIjoiOWJmMGRiOWQzMmU4NDI4ZWFlMTIwZjg2OTU5MWI5ZjMiLCJwIjoiaiJ9)

**Review by sohbaker — COMMENTED** [review]
Code LGTM. If it is related to the ticket that Tanya asked about, I have a follow-up question.

**Comment by Genyus** [comment]
Yes, this is related to the skills check export

**Comment by sohbaker** [comment]
Thanks for confirming @Genyus. My follow-up question is whether the Airtable logs are linked correctly on the Jira ticket? 

Under 'Steps to reproduce', it says to compare the first link to the second link, though the second doesn't link to a log (it links to the enrolled students). I wasn't able to compare and a little confused what I needed to look at.

**Comment by Genyus** [comment]
Looks like Efua removed the temporary table.

**Review by tanyapowell — APPROVED** [review]

**Pull request merged**
