### PR TITLE
Installs Members plugin

### PR DESCRIPTION
**Pull request by Genyus**
- enables [custom role management](https://staging.codingblackfemales.com/jobs/wp/wp-admin/admin.php?page=roles)
- updates Composer dependencies

### CODE REVIEW

**Comment by tanyapowell** [comment]
What's the difference between the `Customer` and `Employer` roles?

**Comment by Genyus** [comment]
> What's the difference between the `Customer` and `Employer` roles?

`Customer` is the WooCommerce equivalent of the `Subscriber` role, while `Employer` is a WP Job Manager role granted to users who've posted an ad.

**Comment by tanyapowell** [comment]
Is there a way to combine these roles? Having so many could be confusing for content managers

**Comment by Genyus** [comment]
Nope. Different purposes, different plugins.

**Pull request merged**
